### ISSUE TITLE
Problem with codec Lepton

### ISSUE THREAD

**Issue by Jamaika1** [meganz/mingw-std-threads#56]
I know that the codec will not compile under Windows. This is an unfinished project.
However, it bothers me a error in ioutil.cc.
```
std::thread discard_stderr(std::bind(&discard_stderr, retval.pipe_stderr));
discard_stderr.detach();
```

**Comment by nmcclatchey** [comment]
This is not a bug in the library. You are passing a pointer to the `std::thread` instance named `discard_stderr`, not to the function with the same name. The implementation is correctly failing to invoke the pointer-to-thread.

**Comment by nmcclatchey** [comment]
It would help to push the error as close as possible to the erroneous user code. For example, placing `static_assert(std::is_invocable<Func, Args...>::value, "Thread must be able to invoke its argument.");` into the thread constructor would reduce the large template-instantiation error to a few lines with an immediately-relevant error message.

The problem is that `std::is_invocable` is a C++17 feature. Recent versions of of MinGW / GCC permit `std::__is_invocable` even in C++11, but using this would introduce a dependency on the version of MinGW, which leads to strange errors that are difficult to track down.

With that in mind, the correct solution is in two parts:
* for C++17 and above, use `std::is_invocable`.
* for C++11 & C++14, implement it ourselves, as part of `mingw.invoke.h`. This will require heavy use of SFINAE.

**Comment by Jamaika1** [comment]
How do you write it correctly in this case?
```
#include "mingw.invoke.h"
…
static_assert(std::is_invocable<IOUtil::start_subprocess::discard_stderr, void>::value
```
The author corrected the line by changing the end of the command discard_stderr.
```
        std::thread discard_stderr_t(std::bind(&discard_stderr, retval.pipe_stderr));
        discard_stderr_t.detach();
```

**Comment by nmcclatchey** [comment]
The author's response is correct; his/her code had an error, and changing the name of the `std::thread` instance resolved the error.

All that the MinGW std threads library can do is make such errors easier to identify.
